
- name: Copy a single file
  win_copy:
    src: filebeat-6.5.3-windows-x86_64.zip
    dest: "{{ win_path }}\\filebeat-6.5.3-windows-x86_64.zip"

- name: create filebeat folder
  win_file:
    path: "{{ filebeat_win_path }}"
    state: directory

- name: Enshure {{ win_path }} exists
  win_file: path={{ filebeat_win_path }} state=directory

- name: extract filebeat zip
  win_unzip:
    src: "{{ win_path }}\\filebeat-6.5.3-windows-x86_64.zip"
    dest: "{{ filebeat_win_path }}"
    rm: true

- name: configure filebeat agent
  win_template:
    src: filebeat.confwin.j2
    dest: "{{ filebeat_win_path }}\\filebeat.yml"
    
- name: uninstall filebeat
  win_command: powershell.exe -ExecutionPolicy ByPass -File {{ filebeat_win_path }}\\uninstall-service-filebeat.ps1

- name: install filebeat
  win_command: powershell.exe -ExecutionPolicy ByPass -File {{ filebeat_win_path }}\\install-service-filebeat.ps1

- name: Ensure filebeat service is started
  win_service: name=filebeat start_mode=auto state=started
