
- name: create filebeat folder
  win_file:
    path: "{{ win_path }}"
    state: directory

- name: Copy filebeat zip
  win_copy:
    src: filebeat-6.5.3-windows-x86_64.zip
    dest: "{{ win_path }}\\filebeat-6.5.3-windows-x86_64.zip"

- name: Stop filebeat service 
  win_service: 
    name: filebeat
    state: stopped
  ignore_errors: true

- name: extract filebeat zip
  win_unzip:
    src: "{{ win_path }}\\filebeat-6.5.3-windows-x86_64.zip"
    dest: "{{ win_path }}"
    rm: true

- name: configure filebeat agent
  win_template:
    src: filebeat.confwin.j2
    dest: "{{ filebeat_win_path }}\\filebeat.yml"
    
- name: uninstall filebeat
  #win_command: "powershell.exe -ExecutionPolicy ByPass -File {{ filebeat_win_path }}\\uninstall-service-filebeat.ps1"
  win_shell : "{{ filebeat_win_path }}\\uninstall-service-filebeat.ps1"

- name: install filebeat
  #win_command: "powershell.exe -ExecutionPolicy ByPass -File {{ filebeat_win_path }}\\install-service-filebeat.ps1"
  win_shell : "{{ filebeat_win_path }}\\install-service-filebeat.ps1"

- name: Start filebeat service 
  win_service: 
    name: filebeat
    state: started

- name: Ensure filebeat service is started
  win_service: name=filebeat start_mode=auto state=started