---
- hosts: logstash
  remote_user: root
  roles:
    - { role: logstash, tags: ["logstash"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global_vars/global.yaml"

- hosts: nginx
  remote_user: root
  roles:
    - { role: nginx, tags: ["nginx"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global_vars/global.yaml"

- hosts: agents
  remote_user: root
  roles:
    - { role: telegraf, tags: ["agents, telegraf"] }
    - { role: filebeat, tags: ["agents, filebeat"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global_vars/global.yaml"