---
- hosts: logstash
  remote_user: root
  roles:
    - { role: logstash, tags: ["logstash"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global.yaml"

- hosts: nginx
  remote_user: root
  roles:
    - { role: nginx, tags: ["nginx"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global.yaml"

- hosts: agents
  remote_user: root
  gather_facts: no
  roles:
    - { role: telegraf, tags: ["agents, telegraf"] }
    - { role: filebeat, tags: ["agents, filebeat"] }
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_connection: winrm
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global.yaml"
    - name: Include vault
      include_vars: "{{ playbook_dir }}/hospital/vars.yaml"
    - name: debug
      debug:
        msg: "{{ vars }}"
    - name: another debug
      debug: 
        msg: "{{ ansible_connection }}"
    - name: another debug
      debug: 
        msg: "{{ ansible_pass }}"