---
- hosts: logstash
  remote_user: root
  roles:
    - { role: logstash, tags: ["logstash"] }
  vars_files:
    - "{{ playbook_dir }}/global.yaml"

- hosts: nginx
  remote_user: root
  roles:
    - { role: nginx, tags: ["nginx"] }
  vars_files:
    - "{{ playbook_dir }}/global.yaml"

- hosts: agents
  remote_user: root
  gather_facts: no
  roles:
    - { role: telegraf, tags: ["agents, telegraf"] }
    - { role: filebeat, tags: ["agents, filebeat"] }
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_connection: winrm
  vars_files:
    - "{{ playbook_dir }}/global.yaml"
    - "{{ playbook_dir }}/hospital/vars.yaml"
