---
- hosts: logstash
  remote_user: root
  roles:
    - { role: logstash, tags: ["logstash"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global.yaml"

- hosts: nginx
  remote_user: root
  roles:
    - { role: nginx, tags: ["nginx"] }
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/global.yaml"

- hosts: agents
  remote_user: root
  roles:
    - { role: telegraf, tags: ["agents, telegraf"] }
    - { role: filebeat, tags: ["agents, filebeat"] }
  vars:
    ansible_winrm_server_cert_validation: ignore
  pre_tasks:
    - name: Include vars
      include_vars: ["{{ playbook_dir }}/global.yaml", "{{ playbook_dir }}/hospital/vars.yaml"]