
- name: create telegraf folder
  win_file:
    path: "{{ win_path }}"
    state: directory

- name: Copy telegraf artifact to telegraf folder
  win_copy:
    src: telegraf-1.9.0_windows_amd64.zip
    dest: "{{ win_path }}\\telegraf-1.9.0_windows_amd64.zip"

- name: stop telegraf service
  win_service: 
    name: Telegraf
    state: stopped
  ignore_errors: yes  

- name: uninstall telegraf service
  win_command: "{{ telegraf_win_path}}\\telegraf.exe --service uninstall"  

- name: extract telegraf zip
  win_unzip:
   src: "{{ win_path }}\\telegraf-1.9.0_windows_amd64.zip"
   dest: "{{ win_path }}"
   rm: true

- name: configure telegraf agent
  win_template:
    src: telegraf.confwin.j2
    dest: "{{ telegraf_win_path }}\\telegraf.conf"

- name: install telegraf service
  win_command: "{{ telegraf_win_path}}\\telegraf.exe --service install --config {{ telegraf_win_path}}\\telegraf.conf"

- name: start telegraf service
  win_service: 
    name: Telegraf
    state: started

- name: Ensure filebeat service is started
  win_service: name=Telegraf start_mode=auto state=started
